# Wheel mass in Kilograms
mass: 0.5        # Wheel mass in Kg     
# Wheel radius in meters
radius: 0.0331    # Wheel radius in m  
# Wheel length in meters, considering is as a cylinder
length: 0.025     # Wheel length in m, considering is as a cylinder
# Name of the mesh files. Leave it empty ('') to have a red wheel.  
mesh: '../components/wheel.stl'          # Name of the mesh files. Leave it empty ('') to have a red wheel
scale: ''
# Offset distance, in meters, from the outer face of the base to the center of the wheel.
x_offset: 0.17
# Offset distance, in meters, from the outer face of the base to the inner face of the wheel. 
# The outer face of the base is the reference so, if the wheels are inside the base the value must be
# negative. If the wheels are outside, must be positive.
y_offset: 0.003
# Offset distance, in meters, from the bottom face of the base to the center of the wheel.
z_offset: 0.017
