scale: '0.5 0.5 0.5'
base:
  mass: 0.02
  size:
    x: 0.005
    y: 0.005
    z: 0.001
  dx: 0.08 #-0.5 # Can we use variable inside yaml files? ${-base_length/2*0.69}
  dy: 0.0
  dz: 0.0
  mesh: 'caster_base.stl'

hub:
  mass: 0.02
  size:
    x: 0.001
    y: 0.001
    z: 0.001
  dx: 0.08 #-0.5 # Can we use variable inside yaml files? ${-base_length/2*0.69}
  dy: 0.0
  dz: 0.0
  mesh: 'caster_wheel_support.stl'

wheel:
  #  <xacro:property name="caster_wheel_mass" value="0.5" /> <!-- in kg-->
  mass: 0.01        # Wheel mass in Kg
  radius: 0.002     # Wheel radius in m
  length: 0.004      # Wheel length in m, considering is as a cylinder
  mesh: 'caster_wheel.stl'          # Name of the mesh files. Leave it empty ('') to have a red wheel
  x_offset: 0.035
  dx: -0.005  # ${-caster_base_size/2.0*0.8}
  dy: -1 # TODO unused
  dz: -0.01 # TODO can we use ${-caster_base_size} inside yaml?